"use client";
import {useEffect,useState} from 'react';
import {useTheme} from 'next-themes';
import {Bell,Check,ChevronDown,Download,LogOut,Settings2,User,History} from 'lucide-react';
import {toast} from 'sonner';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {AnalyticsPanel} from './report-panel';
import {StudyGoal} from './study-goal';
import {dateKey,type StudyData} from '@/lib/edutrack';
import {PriorityGuide,useDeadlineNotices,markDeadlineNotices} from './deadline-reminders';
import {Panel,PanelHeader} from './app';
import {Heading,type ViewProps} from './views';
import {Choice} from './forms';
import Link from './link';
import {api} from './account-store'; import {navigateTo} from './navigation';
export function UserMenu({data,mode}:{data:StudyData;mode:'account'|'demo'}){
  async function logout(){await window.edutrackFlush?.();try{if(mode==='account')await api('/auth/logout',{});localStorage.removeItem('edutrack-mode');await navigateTo('/login');}catch{toast.error('Não foi possível sair. Tente novamente.');}}
  return <DropdownMenu><DropdownMenuTrigger asChild><button className="profile-button" aria-label="Abrir menu do usuário"><span className="avatar">{data.profile.name.charAt(0)}</span><span>{data.profile.name.split(' ')[0]}</span><ChevronDown size={15}/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="user-menu"><DropdownMenuLabel>{data.profile.name}<small>{data.profile.email||'Demonstração local'}</small></DropdownMenuLabel><DropdownMenuSeparator/>{[['/perfil','Meu perfil',User],['/configuracoes','Configurações',Settings2],['/notificacoes','Notificações',Bell],['/historico','Histórico de alterações',History]].map(([href,label,Icon])=>{const Component=Icon as typeof User;return <DropdownMenuItem asChild key={href as string}><Link href={href as string}><Component size={17}/>{label as string}</Link></DropdownMenuItem>;})}<DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>void logout()}><LogOut size={17}/>{mode==='demo'?'Sair da demonstração':'Sair da conta'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}
export function AccountSettings({data,setData}:ViewProps){const {setTheme}=useTheme();const mode=data.profile.id?'account':'demo';return <><Heading title="Tudo sob seu controle" description="Personalize a aparência, seus lembretes e seus dados."/><div className="settings-stack"><StudyGoal data={data} setData={setData}/><Panel><PanelHeader title="Aparência"/><Choice id="theme-preference" label="Tema do EduTrack" value={data.profile.theme||'system'} onChange={theme=>{setTheme(theme);setData(p=>({...p,profile:{...p.profile,theme:theme as 'system'|'dark'|'light'}}));}} options={[{value:'system',label:'Acompanhar o dispositivo'},{value:'light',label:'Claro'},{value:'dark',label:'Escuro'}]}/></Panel><Panel><PanelHeader title="Notificações"/><label className="preference-switch"><input type="checkbox" checked={data.profile.notificationsEnabled!==false} onChange={e=>setData(p=>({...p,profile:{...p.profile,notificationsEnabled:e.target.checked}}))}/><span>Lembrar de tarefas próximas e atrasadas no aplicativo</span></label><p className="section-description">Avisos por prioridade: Urgente 7 dias, Alta 3, Normal 2 e Baixa 1 dia antes do prazo. Atualizam a cada minuto com a aba visível. Não enviamos e-mail nem push com o app fechado.</p><Link className="text-link" href="/notificacoes">Abrir minhas notificações</Link></Panel><Panel><PanelHeader title="Conta e segurança"/><p className="section-description">{mode==='account'?`E-mail confirmado: ${data.profile.email}. Sua sessão usa um cookie protegido, e os dados ficam associados à sua conta.`:'Você está na demonstração. Os dados ficam apenas neste navegador.'}</p><Link className="button secondary" href={mode==='account'?'/recuperar-senha':'/cadastro'}>{mode==='account'?'Redefinir minha senha':'Criar minha conta'}</Link></Panel><Panel><PanelHeader title="Seus dados"/><p className="section-description">Baixe uma cópia dos seus registros. Não inclui senha nem tokens de acesso.</p><button className="button secondary" onClick={()=>download(JSON.stringify(data,null,2),`edutrack-${dateKey()}.json`,'application/json')}><Download size={17}/>Exportar meus dados</button></Panel><Panel><PanelHeader title="Integrações de estudo"/><p className="section-description">O Classroom permite leitura e importação manual após configurar o servidor e autorizar sua conta Google. Gerencie a conexão na aba Integrações.</p><Link className="text-link" href="/integracoes">Gerenciar integrações</Link></Panel></div></>;}
export function Notifications({data}:ViewProps){
  const {items,error,unread}=useDeadlineNotices();
  async function mark(id?:string){try{await markDeadlineNotices(data,items,id);}catch{toast.error('Não foi possível marcar como lida.');}}
  return <><Heading title="Seus próximos lembretes" description="Avisos por importância e prazo, atualizados com a aba aberta." action={<button className="button secondary" onClick={()=>void mark()} disabled={!unread}><Check size={17}/>Marcar todas como lidas</button>}/><PriorityGuide/><Panel className="deadline-notices">{error&&<p role="alert">{error}</p>}{!items.length&&!error&&<div className="empty-state"><Bell size={30}/><h2>Tudo tranquilo por aqui</h2><p>{data.profile.notificationsEnabled===false?'Os lembretes estão desativados nas configurações.':'Os avisos aparecerão conforme o prazo e a prioridade das suas tarefas.'}</p></div>}{items.map(i=><article className={`notice-row ${i.read_at?'read':''}`} key={i.id}><Bell size={20}/><div><strong>{i.title}</strong><p className={`task-deadline-message deadline-${i.tone}`}>{i.message}</p><p>Prazo: {i.due.split('-').reverse().join('/')} · Prioridade {i.priorityLabel} · {i.read_at?'Lida':'Não lida'}</p><Link className="text-link" href="/tarefas">Ver tarefas</Link></div>{!i.read_at&&<button className="icon-button" aria-label={`Marcar ${i.title} como lida`} onClick={()=>void mark(i.id)}><Check size={18}/></button>}</article>)}</Panel></>;
}
type HistoryItem={id:string;title:string;changed_at:string;changes_json:Record<string,{from:unknown;to:unknown}|boolean>};
const fields:Record<string,string>={status:'Status',priority:'Prioridade',due:'Prazo',title:'Título',description:'Anotações',subject:'Disciplina',difficulty:'Dificuldade',estimatedMinutes:'Tempo estimado'};
const values:Record<string,string>={TODO:'A fazer',IN_PROGRESS:'Em andamento',COMPLETED:'Concluída',CANCELLED:'Cancelada',LOW:'Baixa',MEDIUM:'Média',HIGH:'Alta',URGENT:'Urgente',EASY:'Fácil',HARD:'Difícil'};
export function HistoryView({data}:ViewProps){const [items,setItems]=useState<HistoryItem[]>([]),[error,setError]=useState('');useEffect(()=>{if(!data.profile.id)return;void (async()=>{await window.edutrackFlush?.();setItems((await api<{items:HistoryItem[]}>('/history')).items);})().catch(()=>setError('Não foi possível carregar o histórico.'));},[data]);return <><Heading title="Cada mudança tem uma história" description="Criações e alterações de tarefas registradas pelo backend."/><Panel>{!data.profile.id?<p className="empty-message">O histórico auditável está disponível nas contas. A demonstração permanece local.</p>:error?<p role="alert">{error}</p>:!items.length?<p className="empty-message">Nenhuma alteração registrada ainda.</p>:items.map(i=><article className="audit-row" key={i.id}><strong>{i.title}</strong><time>{new Date(i.changed_at).toLocaleString('pt-BR')}</time><ul>{Object.entries(i.changes_json).filter(([key])=>key!=='subject').map(([key,value])=><li key={key}>{key==='created'?'Tarefa criada':`${fields[key]||key}: ${typeof value==='object'?`${values[String(value.from)]||String(value.from??'—')} → ${values[String(value.to)]||String(value.to??'—')}`:''}`}</li>)}</ul></article>)}</Panel></>;}
export {AnalyticsPanel} from './report-panel';
function download(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Reports(props:ViewProps){return <><Heading title="Um olhar mais completo" description="Explore seus registros por período e disciplina."/><AnalyticsPanel data={props.data}/></>;}
