"use client";
import { useEffect,useState,type Dispatch,type SetStateAction } from "react";
import Link from "./link";
import { ArrowLeft,ArrowRight,BookOpen,CalendarDays,Check,Clock3,Download,Edit3,Pause,Play,Plus,RotateCcw,Search,ShieldCheck,Sparkles,Target,Trash2 } from "lucide-react";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { Panel,PanelHeader,SubjectCards,StudyChart,TaskRow } from "./app";
import {ClassroomDeliveryStatus} from './classroom-deliveries';
import { Choice } from "./forms";
import {TaskDetails} from './task-details';
import {useStudyTimer} from './use-study-timer';
import {resetStudyTimer} from '@/lib/study-timer.mjs';
import { dateKey,dueLabel,formatMinutes,lastSevenDays,seedData,type StudyData,type Task } from "@/lib/edutrack";
import {compareTasks} from '@/lib/study-planning';
import {DeadlineBanner,PriorityGuide,useStudyDay} from './deadline-reminders';
export type ViewProps={data:StudyData;setData:Dispatch<SetStateAction<StudyData>>;toggle:(id:string)=>void;editTask:(task?:Task)=>void;newSubject:()=>void;page:string};
export function Heading({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="page-heading"><div><div className="eyebrow">SEU ESPAÇO PARA EVOLUIR</div><h1>{title}<span className="heading-dot">.</span></h1><p>{description}</p></div>{action}</div>;}
export function Tasks({data,setData,toggle,editTask}:ViewProps){
const [detailId,setDetailId]=useState("");
const today=useStudyDay();
const [query,setQuery]=useState("");const [subject,setSubject]=useState("all");const [tab,setTab]=useState("pending");const [priority,setPriority]=useState("all");const filtered=data.tasks.filter(t=>(tab==="all"||(tab==="done"?t.done:!t.done&&t.status!=="CANCELLED"))&&(subject==="all"||t.subjectId===subject)&&(priority==="all"||t.priority===priority)&&t.title.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))).sort((a,b)=>compareTasks(a,b,today));
function remove(task:Task){setData(p=>({...p,tasks:p.tasks.filter(t=>t.id!==task.id)}));toast("Tarefa removida.",{action:{label:"Desfazer",onClick:()=>setData(p=>({...p,tasks:[...p.tasks,task]}))}});}
return <><Heading title="Uma tarefa de cada vez" description="Tire as ideias da cabeça e dê espaço para o que importa." action={<button className="button primary" onClick={()=>editTask()}><Plus size={18}/>Nova tarefa</button>}/><DeadlineBanner data={data}/><PriorityGuide/><ClassroomDeliveryStatus/><Panel><div className="filter-row"><label className="search-field"><Search size={18}/><input aria-label="Buscar tarefas" placeholder="Buscar uma tarefa..." value={query} onChange={e=>setQuery(e.target.value)}/></label><Choice id="filter-subject" label="Disciplina" value={subject} onChange={setSubject} options={[{value:"all",label:"Todas as disciplinas"},...data.subjects.map(s=>({value:s.id,label:s.name}))]}/><Choice id="filter-priority" label="Prioridade" value={priority} onChange={setPriority} options={[{value:"all",label:"Todas"},{value:"urgente",label:"Urgente"},{value:"alta",label:"Alta"},{value:"normal",label:"Normal"},{value:"baixa",label:"Baixa"}]}/></div><Tabs value={tab} onValueChange={setTab}><TabsList className="task-tabs"><TabsTrigger value="pending">Pendentes</TabsTrigger><TabsTrigger value="done">Concluídas</TabsTrigger><TabsTrigger value="all">Todas</TabsTrigger></TabsList>{["pending","done","all"].map(value=><TabsContent value={value} key={value}>{filtered.length?filtered.map(task=><div className="editable-task" key={task.id}><TaskRow task={task} data={data} toggle={toggle}/><button className="icon-button" aria-label={`Detalhes de ${task.title}`} onClick={()=>setDetailId(task.id)}><ArrowRight size={16}/></button><button className="icon-button" aria-label={`Editar ${task.title}`} onClick={()=>editTask(task)}><Edit3 size={16}/></button><button className="icon-button" aria-label={`Remover ${task.title}`} onClick={()=>remove(task)}><Trash2 size={16}/></button></div>):<div className="empty-state"><ListIcon/><h2>{query?"Nenhuma tarefa encontrada":"Espaço para um novo começo"}</h2><p>{query?"Tente outro título ou ajuste os filtros.":"Adicione uma tarefa e escolha seu próximo passo."}</p><button className="button secondary" onClick={()=>editTask()}>Criar tarefa</button></div>}</TabsContent>)}</Tabs></Panel><TaskDetails task={data.tasks.find(t=>t.id===detailId)} data={data} toggle={toggle} editTask={editTask} onClose={()=>setDetailId("")}/></>;
}
function ListIcon(){return <Check className="empty-icon" size={27}/>;}
export function Subjects(props:ViewProps){const {data,page,toggle,newSubject,editTask}=props;const today=useStudyDay();const id=page.split("/")[1];if(id){const subject=data.subjects.find(s=>s.id===id);if(!subject)return <div className="empty-state"><h1>Disciplina não encontrada</h1><Link className="button primary" href="/disciplinas">Ver disciplinas</Link></div>;const tasks=data.tasks.filter(t=>t.subjectId===id).sort((a,b)=>compareTasks(a,b,today));return <><Link className="back-link" href="/disciplinas"><ArrowLeft size={17}/>Todas as disciplinas</Link><Heading title={subject.name} description={subject.description||"Seu espaço para explorar este assunto."} action={<button className="button primary" onClick={()=>editTask()}><Plus size={18}/>Nova tarefa</button>}/><div className="detail-stats"><Panel><BookOpen/><strong>{tasks.length}</strong><span>Tarefas cadastradas</span></Panel><Panel><Clock3/><strong>{formatMinutes(data.sessions.filter(s=>s.subjectId===id).reduce((sum,s)=>sum+s.minutes,0))}</strong><span>Tempo registrado</span></Panel></div><Panel><PanelHeader title="Tarefas desta disciplina"/>{tasks.map(task=><div key={task.id} className="editable-task"><TaskRow task={task} data={data} toggle={toggle}/><button className="icon-button" aria-label={`Editar ${task.title}`} onClick={()=>editTask(task)}><Edit3 size={17}/></button></div>)}{!tasks.length&&<p className="empty-message">Nenhuma tarefa por aqui ainda.</p>}</Panel></>;}
return <><Heading title="O que você quer aprender?" description="Organize matérias, cursos e assuntos em um único lugar." action={<button className="button primary" onClick={newSubject}><Plus size={18}/>Nova disciplina</button>}/><SubjectCards data={data}/><div className="tip-panel"><Sparkles size={23}/><div><h3>Seu aprendizado não precisa caber em uma grade.</h3><p>Crie uma disciplina para qualquer assunto que desperte sua curiosidade.</p></div></div></>;}
export {CalendarView} from './study-calendar';
export function Sessions({data,setData}:ViewProps){
const {timer,setTimer,loaded}=useStudyTimer(data.profile.id,data.subjects[0]?.id||"none");const [now,setNow]=useState(()=>Date.now());const [manualSubject,setManualSubject]=useState(data.subjects[0]?.id||"none");
useEffect(()=>{if(!timer.startedAt)return;const id=setInterval(()=>setNow(Date.now()),1000);return ()=>clearInterval(id);},[timer.startedAt]);
const elapsed=timer.accumulated+(timer.startedAt?Math.max(0,now-timer.startedAt):0);const seconds=Math.floor(elapsed/1000);const display=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
function finish(){const minutes=Math.floor((timer.accumulated+(timer.startedAt?Date.now()-timer.startedAt:0))/60000);if(minutes<1){toast("Estude pelo menos um minuto antes de registrar a sessão.");return;}saveSession(timer.subject,minutes,dateKey());setTimer(t=>({...t,accumulated:0,startedAt:null}));}
function reset(){setTimer(resetStudyTimer);setNow(Date.now());toast.success("Cronômetro resetado. Nenhuma sessão registrada foi alterada.");}
function saveSession(subjectId:string,minutes:number,date:string){setData(p=>({...p,sessions:[...p.sessions,{id:crypto.randomUUID(),subjectId:subjectId==="none"?"":subjectId,minutes,date}]}));toast.success("Sessão registrada. Cada passo conta!");}
return <><Heading title="Este tempo é seu" description="Escolha um assunto, respire fundo e comece. No seu ritmo."/>
  <div className="session-layout"><Panel className="timer-panel">
    <span className="pill purple">MODO FOCO</span><h2>Uma coisa de cada vez.</h2>
    <div className="timer-display" role="timer" aria-label={`Tempo decorrido: ${Math.floor(seconds/60)} minutos e ${seconds%60} segundos`}>{display}</div>
    <Choice id="timer-subject" label="Vou estudar" value={timer.subject} onChange={subject=>setTimer(t=>({...t,subject}))} options={[{value:"none",label:"Estudo livre"},...data.subjects.map(s=>({value:s.id,label:s.name}))]}/>
    <div className="timer-actions">
      <button type="button" className="button primary" disabled={!loaded} onClick={()=>{const at=Date.now();setNow(at);setTimer(t=>t.startedAt?{...t,accumulated:t.accumulated+at-t.startedAt,startedAt:null}:{...t,startedAt:at});}}>{timer.startedAt?<><Pause size={18}/>Pausar</>:<><Play size={18}/>{seconds?"Continuar":"Começar"}</>}</button>
      <button type="button" className="button secondary" onClick={finish} disabled={!loaded||seconds<60}>Concluir sessão</button>
      <AlertDialog>
        <AlertDialogTrigger asChild><button type="button" className="button secondary" disabled={!loaded||(elapsed<=0&&timer.startedAt===null)}><RotateCcw size={18}/>Resetar</button></AlertDialogTrigger>
        <AlertDialogContent className="edu-dialog">
          <AlertDialogHeader><AlertDialogTitle>Resetar o cronômetro?</AlertDialogTitle><AlertDialogDescription>O tempo desta sessão será descartado e o cronômetro ficará parado em 00:00. A disciplina selecionada e os estudos já registrados serão mantidos.</AlertDialogDescription></AlertDialogHeader>
          <AlertDialogFooter><AlertDialogCancel className="button secondary">Cancelar</AlertDialogCancel><AlertDialogAction className="button primary" onClick={reset}>Sim, resetar</AlertDialogAction></AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
    <p className="form-note">O cronômetro continua ao navegar. Concluir registra os minutos completos; resetar apenas descarta o tempo atual.</p>
  </Panel><Panel><PanelHeader title="Já estudou hoje?"/><p className="section-description">Registre também as sessões feitas longe da tela.</p><form className="edu-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const minutes=Number(form.get("minutes"));const date=String(form.get("date"));if(!Number.isInteger(minutes)||minutes<1||minutes>1440||!date||date>dateKey()){toast.error("Informe de 1 a 1440 minutos e uma data até hoje.");return;}saveSession(manualSubject,minutes,date);e.currentTarget.reset();}}><Choice id="manual-subject" label="Disciplina" value={manualSubject} onChange={setManualSubject} options={[{value:"none",label:"Estudo livre"},...data.subjects.map(s=>({value:s.id,label:s.name}))]}/><div className="field"><label htmlFor="minutes">Duração em minutos</label><input id="minutes" name="minutes" type="number" min={1} max={1440} step={1} defaultValue={25} required/></div><div className="field"><label htmlFor="session-date">Data do estudo</label><input id="session-date" type="date" name="date" max={dateKey()} defaultValue={dateKey()} required/></div><button className="button primary">Registrar estudo</button></form></Panel></div><Panel className="history-panel"><PanelHeader title="Suas últimas sessões"/>{[...data.sessions].reverse().slice(0,10).map(s=><div key={s.id} className="history-row"><span className="metric-icon purple"><Clock3 size={18}/></span><div><strong>{data.subjects.find(sub=>sub.id===s.subjectId)?.name||"Estudo livre"}</strong><span>{dueLabel(s.date)}</span></div><strong>{formatMinutes(s.minutes)}</strong></div>)}</Panel></>;}
export function ProgressView({data}:ViewProps){const minutes=lastSevenDays(data.sessions).reduce((sum,s)=>sum+s.minutes,0);const days=new Set(data.sessions.filter(s=>lastSevenDays([]).some(d=>d.date===s.date)).map(s=>s.date)).size;return <><Heading title="Olhe o caminho que você fez" description="Registros reais de dedicação. Sem competição, sem julgamentos."/><div className="detail-stats"><Panel><Clock3/><strong>{formatMinutes(minutes)}</strong><span>Nos últimos 7 dias</span></Panel><Panel><Target/><strong>{days} de 7</strong><span>Dias com estudo registrado</span></Panel></div><div className="session-layout"><Panel><PanelHeader title="Seu ritmo na última semana"/><StudyChart data={data}/></Panel><Panel><PanelHeader title="Tempo por disciplina"/>{data.subjects.map(subject=>{const total=data.sessions.filter(s=>s.subjectId===subject.id).reduce((sum,s)=>sum+s.minutes,0);const all=data.sessions.reduce((sum,s)=>sum+s.minutes,0);return <div className="distribution-row" key={subject.id}><div><span>{subject.name}</span><strong>{formatMinutes(total)}</strong></div><Progress value={all?total/all*100:0} className={`subject-progress ${subject.color}`} aria-label={`Participação de ${subject.name} no tempo total`}/></div>;})}</Panel></div><div className="tip-panel"><ShieldCheck size={24}/><div><h3>Tempo é um registro de dedicação.</h3><p>Esses números são calculados a partir das sessões salvas. Eles não medem, por si só, o domínio de um assunto.</p></div></div></>;}
export function AgentView({data,editTask}:ViewProps){const [example,setExample]=useState("plan");const pending=data.tasks.filter(t=>!t.done);return <><Heading title="Um novo olhar para seus estudos" description="Conheça a proposta do seu futuro assistente acadêmico."/><div className="agent-workspace"><div className="agent-orb"><Sparkles size={34}/></div><span className="pill purple">PRÉVIA DO AGENTE · SEM MODELO CONECTADO</span><h2>Mais clareza para<br/>dar o próximo passo.</h2><p>O agente interpretará seu progresso e ajudará a organizar suas ideias. Você continua no controle das ações.</p><div className="agent-suggestions"><button className="button secondary" onClick={()=>setExample("plan")}><CalendarDays size={17}/>Organizar minha semana</button><button className="button secondary" onClick={()=>setExample("progress")}><Target size={17}/>Entender meu progresso</button></div><Panel className="agent-preview"><div className="insight-label"><Sparkles size={18}/>Exemplo de experiência</div><p>{example==="plan"?`Seu painel tem ${pending.length} tarefas pendentes. Você pode revisar os prazos e escolher uma para começar.`:`Você registrou ${formatMinutes(lastSevenDays(data.sessions).reduce((sum,s)=>sum+s.minutes,0))} nos últimos 7 dias. A página de progresso mostra a distribuição por dia e disciplina.`}</p><span className="form-note">Resumo calculado localmente. Este texto não foi gerado por IA.</span><button className="button primary" onClick={()=>editTask()}>Planejar uma tarefa manualmente<ArrowRight size={17}/></button></Panel><div className="agent-principles"><span><ShieldCheck size={17}/>Ações autorizadas</span><span><Clock3 size={17}/>Histórico auditável no backend</span></div></div></>;}
export function ProfileView({data,setData}:ViewProps){return <><Heading title="Seu espaço, do seu jeito" description="Comece pelo que faz sentido para você."/><Panel className="profile-panel"><div className="profile-intro"><span className="avatar large-avatar">{data.profile.name.charAt(0)}</span><div><h2>{data.profile.name}</h2><span className="pill purple">{data.profile.id?"E-mail confirmado":"Perfil de demonstração"}</span>{data.profile.email&&<p className="muted small">{data.profile.email}</p>}</div></div><form className="edu-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get("name")||"").trim();if(!name)return;setData(p=>({...p,profile:{...p.profile,name,goal:String(f.get("goal")||"").trim()}}));toast.success("Perfil atualizado.");}}><div className="field"><label htmlFor="profile-name">Como podemos chamar você?</label><input id="profile-name" name="name" defaultValue={data.profile.name} required maxLength={80}/></div><div className="field"><label htmlFor="profile-goal">Meu objetivo de estudo</label><textarea id="profile-goal" name="goal" defaultValue={data.profile.goal} maxLength={300} rows={3}/></div><button className="button primary">Salvar perfil</button><p className="form-note">{data.profile.id?"Suas alterações são salvas na conta. O e-mail de acesso não é alterado aqui.":"Este perfil pertence apenas à demonstração local."}</p></form></Panel></>;}
export function SettingsView({data,setData}:ViewProps){return <><Heading title="Tudo sob seu controle" description="Gerencie sua demonstração e conheça as próximas integrações."/><div className="settings-stack"><Panel><PanelHeader title="Dados desta demonstração"/><p className="section-description">Tarefas, disciplinas, perfil e sessões ficam neste navegador. Eles não são sincronizados entre dispositivos.</p><div className="inline-actions wrap"><button className="button secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`edutrack-${dateKey()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success("Arquivo de dados preparado.");}}><Download size={17}/>Exportar meus dados</button><AlertDialog><AlertDialogTrigger asChild><button className="button secondary">Restaurar exemplos</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restaurar os dados de exemplo?</AlertDialogTitle><AlertDialogDescription>Seu perfil, tarefas, disciplinas e sessões locais serão substituídos. Exporte seus dados antes de continuar se quiser guardá-los.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{const previous=data;setData(seedData());toast("Dados de exemplo restaurados.",{action:{label:"Desfazer",onClick:()=>setData(previous)}});}}>Restaurar exemplos</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></Panel><Panel><PanelHeader title="Conta e segurança"/><p className="section-description">Login, cadastro e recuperação já têm suas telas. A autenticação segura e o envio de e-mails serão conectados ao backend.</p><Link className="text-link" href="/login">Conhecer a tela de acesso<ArrowRight size={17}/></Link></Panel><Panel><PanelHeader title="Lembretes e aparência"/><p className="section-description">A interface acompanha o tamanho da sua tela e respeita a preferência de movimento reduzido do dispositivo. Lembretes por e-mail e notificações estão previstos para uma próxima etapa.</p></Panel></div></>;}
export function HelpView(){return <><Heading title="Vamos simplificar" description="Um pouco de orientação para encontrar seu caminho."/><div className="settings-stack">{[["Por onde eu começo?","Abra Disciplinas e cadastre um assunto. Depois, crie uma tarefa e inicie uma sessão em Sessões de estudo."],["Meus dados estão sendo salvos?","Na demonstração, ficam no navegador. Nas contas, são salvos no banco do servidor. Você pode exportar uma cópia em Configurações."],["Como o tempo é calculado?","O cronômetro usa o tempo decorrido, mesmo ao mudar de página. Ao concluir, salva os minutos completos. Também é possível registrar uma sessão manualmente."],["A IA já está funcionando?","Ainda não. A página do agente apresenta uma prévia identificada. Nenhum dado de estudo é enviado a um modelo nesta versão."],["Já posso criar uma conta real?","Sim. Cadastre-se e confirme o e-mail antes de entrar. No ambiente de testes, abra a caixa de e-mails local. O envio real usa SMTP configurado no servidor."]].map(([q,a])=><details className="faq-item" key={q}><summary>{q}</summary><p>{a}</p></details>)}<Panel><PanelHeader title="Ainda precisa de ajuda?"/><p className="section-description">O canal de atendimento será adicionado antes do lançamento. Nesta etapa, você pode enviar seu feedback na conversa em que o projeto está sendo construído.</p><Link className="text-link" href="/inicio">Conhecer a proposta do EduTrack<ArrowRight size={16}/></Link></Panel></div></>;}
